# Generated by Django 4.1.5 on 2023-02-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscrMail',
            new_name='FeedbackMail',
        ),
    ]
