# Generated by Django 4.1.5 on 2023-01-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('AT', 'Статья'), ('NW', 'Новость')], db_column='type', max_length=7, verbose_name='Тип'),
        ),
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='p_type',
        ),
    ]
