# Generated by Django 4.1.5 on 2023-01-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_censorvoc_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
